version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.05-22.04
    steps:
      - checkout 
      - run:
          name: Build Docker image
          command: docker build -t my-node-app .
      - run:  
          name: Archive Docker image
          command: docker save -o image.tar my-node-app
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

workflows:
  build-workflow:
    jobs:
      - build